Polymorphism
ilz-code/Main pull request #8
Opened 2021-08-08 13:15 UTC by ilz-code

2021-08-09 18:08 UTC, ausmoons requested changes

2021-08-09 18:08 UTC, ausmoons commented on Polymorphism/Firm/Commission.cs
> +        public Commission(string name, string address, string phone, string securityNumber, double hourlyRate, double commissionRate) : base( name, address, phone, securityNumber, hourlyRate)
Sākot ar : base( .. pārnes uz jaunu rindu

2021-08-09 18:08 UTC, ausmoons commented on Polymorphism/Firm/StaffMember.cs
> +        private string name;
_name

2021-08-09 18:08 UTC, ausmoons commented on Polymorphism/Hierarchy/Animal.cs
> +        public virtual void MakeSound()
public virtual void MakeSound() { }

2021-08-09 18:08 UTC, ausmoons commented on Polymorphism/Hierarchy/Mouse.cs
> +                base.Eat(food);
Tu abos gadījumos izpildi base.Eat(food).. to tad varēja nelikt iekšā if

2021-08-09 18:08 UTC, ausmoons commented on Polymorphism/Hierarchy/Program.cs
> +                animal.MakeSound();
Te viss ir vienā lielā čupā..varēji sadalīt metodēs

2021-08-09 18:08 UTC, ausmoons commented on Polymorphism/MakeSounds/Parrot.cs
> +
Tukša lieka rinda. Pārbaudi visus failus

2021-08-09 18:58 UTC, ilz-code commented on Polymorphism/Hierarchy/Mouse.cs
> +                base.Eat(food);
Bet tad tas "if (food is Vegetables)" paliek tukšs, vajadzētu "if (food is not Vegetables)", bet tāds nestrādā, kā to pareizāk izdarīt?

2021-08-09 19:07 UTC, ausmoons commented on Polymorphism/Hierarchy/Mouse.cs
> +                base.Eat(food);
base.Eat(food);

(food !is Vegetables) -- >Tas neders? Es vispār nekad neesmu redzējusi, ka raksta is Vegetable.
{
                 Console.WriteLine(" Mouses are not eating that type of food!");
                _foodEaten = 0;
}

2021-08-09 19:07 UTC, ausmoons commented on Polymorphism/Hierarchy/Mouse.cs
> +                base.Eat(food);
Ja savādāk nevar, atstāj kā ir.. es neesmu pārliecināta par šo. Arī base nekad neesmu izmantojusi.  @EdgarsSalmins Esošais variants ir ok?

2021-08-09 20:14 UTC, ausmoons approved these changes

2021-08-10 07:58 UTC, EdgarsSalmins commented on Polymorphism/DragRace/Program.cs
> +                Thread.Sleep(1000);
Priekš kam Thread.Sleep?

2021-08-10 08:18 UTC, EdgarsSalmins commented on Polymorphism/Hierarchy/Mouse.cs
> +                base.Eat(food);
ja peles need to ēdienu tad man šeit izskatās ka uz Else var base.Eat(food) nesaukt. 
pārējais ir ok...

2021-08-10 08:20 UTC, EdgarsSalmins commented on Polymorphism/DragRace/IAdvancedCar.cs
> +        {
interfeisā metodei {} nevajag. :) šis nāk ar pēdējo .Net versiju default implementation.. nav vajadzības. :) atstājam vienkārši void UseNitrousOxideEngine();

2021-08-10 08:21 UTC, ilz-code commented on Polymorphism/DragRace/Program.cs
> +                Thread.Sleep(1000);
Nebija prasīts, bet es drusku aizrāvos un uztaisīju vizualizāciju "kā tās mašīnītes brauc", lai to varētu paspēt saskatīt, programma jāpiebremzē

2021-08-10 08:22 UTC, EdgarsSalmins commented on Polymorphism/DragRace/ICar.cs
> +        public int Place { get; set; }
interfeisos public neliek. jo pēc noklusējuma viss ir public iekš interfeisa. 
un tās noklusētās implementācijas.. jēga no tām ir tikai tad ja pieliek klāt jaunu mašīnu un tai netiek tādas taisītas.. tad izmantosies šīs.. 
bet visādi citādi es noklusētās implementācijas ņemtu nost.

2021-08-10 08:25 UTC, EdgarsSalmins approved these changes

2021-08-10 08:46 UTC, merged