Tests
ilz-code/Main pull request #9
Opened 2021-08-14 12:06 UTC by ilz-code

2021-08-15 10:04 UTC, ausmoons requested changes
Pārskati visur testa nosaukumus

2021-08-15 10:04 UTC, ausmoons commented on Tests/Polymorphism/DragRace/Dragrace.cs
> +                //Console.Clear();
?

2021-08-15 10:04 UTC, ausmoons commented on Tests/Polymorphism/DragRace/Tesla.cs
> +        }
Pirms metodes 1 tukša rinda

2021-08-19 09:12 UTC, ilz-code commented on Tests/Polymorphism/DragRace/Tesla.cs
> +        }
Izlabots

2021-08-20 18:51 UTC, ausmoons reviewed
Es neredzu, ka kaut kas būtu labots

2021-08-29 17:53 UTC, ausmoons approved these changes

2021-08-29 17:53 UTC, ausmoons commented on Arithmetic/Ex1-IsFifteen/Fifteen.cs
> +                      || num2 == 15
Bez iekavam nevar?

2021-08-30 07:29 UTC, merged